<template>
  <div class="productPage btn-shade">
    <div class="myPage" id="myPage">
      <div id="fc-header">
        <Navbar />
      </div>

      <div class="mask"></div>
      <div class="solution-section-3">
        <div class="fc-container">
          <div class="overview-page-headings">
              <h6 class="productHeadPink text-uppercase">
              Commercial Portfolios
                </h6>
            <h1>
              Deliver delightful property experience and turn tenants into
              advocates
            </h1>
            <p>
              Manage a connected portfolio that lets you act fast & reduce
              costs. Drive an unsurpassed tenant experience fueled by data
              centralization and analytics with sustainable practices at its
              core.
            </p>
            <GetStartedButton />
          </div>
        </div>
      </div>
      <!--workplace-feature-2-->
      <div class="workplace-feature-2">
        <div class="fc-container w-feature-wrapper">
          <div class="row fc-wrapper-pad">
            <div class="col-md-6">
              <h6 class="productHeadPink text-uppercase">
                UNIFIED PROPERTY MANAGEMENT
              </h6>
              <div class="fc-workplace-subhead">
                Reduce complexity and
                <br />cost of O&M
              </div>
              <div class="w-feature-desc">
                Traditionally, CREs have to juggle between tools to keep track
                of multi-vendor building systems, varied service contracts and
                diverse touch points with tenants. They have critical tickets,
                work orders and asset information spread over emails, random
                notes and spreadsheets.Facilio removes all the hassle by
                bringing purchase contracts, vendor data, asset warranty,
                inventory, labour and tenant information in a single unified
                app. Because facilio has all data generated by and within
                buildings into a centralized real time application, you can
                easily drill down on an operational inefficiency thereby saving
                cost and time.
              </div>
            </div>
            <div class="col-md-6">
              <div class="fc-img-src">
                <img
                  src="/images/pm-1.png"
                  alt=" Reduce complexity"
                  title=" Reduce complexity"
                  style="max-width:600px;width:100%;"
                />
              </div>
            </div>
          </div>

          <div class="row fc-wrapper-pad fc-reverse">
            <div class="col-md-6">
              <div class="fc-img-src">
                <img
                  src="/images/pm-2.png"
                  alt="  Provide faster and better support to tenants"
                  title="  Provide faster and better support to tenants"
                  style="max-width:600px;width:100%;"
                />
              </div>
            </div>
            <div class="col-md-6">
              <h6 class="productHeadPink text-uppercase">
                PREMIUM TENANT EXPERIENCE
              </h6>
              <div class="fc-workplace-subhead">
                Provide faster and better support to tenants
              </div>
              <div class="w-feature-desc">
                Today’s tenants want real-time answers. Give them the
                flexibility and choice to connect to you instantly through
                Facilio’s tenant portal and strengthen your tenant relationship.
                Now, tenants can request any service and view its progress which
                helps you ensure transparency and provide a delightful
                experience. Help tenants enjoy an increased uptime of better
                assets using our maintenance and anomaly detection functions.
                You can enable them to track and optimize their utility and
                service expenses in real time so that you can gain a competitive
                edge by building tenants’ trust.
              </div>
            </div>
          </div>

          <div class="row fc-wrapper-pad">
            <div class="col-md-6">
              <h6 class="productHeadPink text-uppercase">SUSTAINABILITY</h6>
              <div class="fc-workplace-subhead">
                Sell a sustainable property
              </div>
              <div class="w-feature-desc">
                With Facilio, you can virtualize all meters and get the benefit
                of metering without the additional expense that traditional
                meters bring. The automated meter reading avoids discrepancies
                with tenants, automatically generates custom invoices, and saves
                a lot of time spent on noting down readings on paper and
                spreadsheets. With all the energy data, Facilio provides heat
                map (on any metric), regression (consumption correlation with
                degree days), load, peak energy, and EnPI analysis to accurately
                boost performance. Plus it alerts immediately on an energy
                inefficiency, to take action right away and save costs.
              </div>
            </div>
            <div class="col-md-6">
              <div class="fc-img-src">
                <img
                  src="/images/wee9.png"
                  alt="Simplified assessment that improves asset lifecycle"
                  title="Simplified assessment that improves asset lifecycle"
                  style="max-width:500px;width:100%;"
                />
              </div>
            </div>
          </div>

          <div class="row fc-wrapper-pad fc-reverse">
            <div class="col-md-6">
              <div class="fc-img-src">
                <img
                  src="/images/fdd-3.png"
                  alt=" Maintain the entire portfolio from a single place"
                  title=" Maintain the entire portfolio from a single place"
                  style="max-width:500px;width:100%;"
                />
              </div>
            </div>
            <div class="col-md-6">
              <h6 class="productHeadPink text-uppercase">
                COMMAND AND CONTROL
              </h6>
              <div class="fc-workplace-subhead">
                Maintain the entire portfolio from a single place
              </div>
              <div class="w-feature-desc">
                In the past, analytics meant painfully harvesting data from slow
                tools and leaving it to stay inactive in multiple silos. Today,
                your teams and domain experts can take action faster and
                proactively with enriched insights from centralized data.
                Facilio’s FDD module also detects and diagnoses equipment
                failure by applying sophisticated rule-base (or simple
                configurable math expressions) in real-time. You can resolve any
                comfort or energy inefficiency by automatic work order dispatch
                or self-set point correction and ensure that your business
                quickly returns to normal always.
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <VideoSeriesBand />

    <!----explore-feature-2-->
    <section class="fc-explore-2">
      <div class="fc-container">
        <div class="row">
          <div class="col-md-6">
            <div class="fc-violet-wrap">
              <h3>Manage multiple tenants with ease</h3>
              <ul class="book-list" id="featurelist">
                <li>
                  <div class="flex-middle2">
                    <div class="f27 pR20">¯</div>
                    <div class="pL20">Service request management</div>
                  </div>
                </li>
                <li>
                  <div class="flex-middle2">
                    <div class="f27 pR20">¯</div>
                    <div class="pL20">Tenant Portal</div>
                  </div>
                </li>
                <li>
                  <div class="flex-middle2">
                    <div class="f27 pR20">¯</div>
                    <div class="pL20">Visitor/GatePass</div>
                  </div>
                </li>
                <li>
                  <div class="flex-middle2">
                    <div class="f27 pR20">¯</div>
                    <div class="pL20">Vendor Portal</div>
                  </div>
                </li>
                <li>
                  <div class="flex-middle2">
                    <div class="f27 pR20">¯</div>
                    <div class="pL20">Vehicle/Gate pass management</div>
                  </div>
                </li>
                <li>
                  <div class="flex-middle2">
                    <div class="f27 pR20">¯</div>
                    <div class="pL20">Raise/track billing</div>
                  </div>
                </li>
                <li>
                  <div class="flex-middle2">
                    <div class="f27 pR20">¯</div>
                    <div class="pL20">Configurable Workflows</div>
                  </div>
                </li>
                <li>
                  <div class="flex-middle2">
                    <div class="f27 pR20">¯</div>
                    <div class="pL20">Purchase Order/Receipt tracking</div>
                  </div>
                </li>
                <li>
                  <div class="flex-middle2">
                    <div class="f27 pR20">¯</div>
                    <div class="pL20">Lease management</div>
                  </div>
                </li>
                <li>
                  <div class="flex-middle2">
                    <div class="f27 pR20">¯</div>
                    <div class="pL20">Tenant communications via broadcast</div>
                  </div>
                </li>
              </ul>
              <p class="pL20 fc-see-all" id="featureMore">See all features</p>
            </div>
          </div>
          <div class="col-md-6">
            <div class="fc-gray-wrap">
              <h3>Trusted by forward-thinking enterprises across the globe</h3>
              <div class="fc-less-pad">
                <img src="/images/customer-logo/logo-left/logo.png" />
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!----explore-feature-2-->
  <Footer />

  </div>
</template>

<script>
import GetStartedButton from "../../components/GetStartedButton";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";
import VideoSeriesBand from "../../components/VideoSeriesBand";

export default {
  components: {
    GetStartedButton,
     Navbar,Footer,
    VideoSeriesBand
  },
  mounted: function() {
    $(document).click(function(e) {
      if (!$(e.target).is(".fc-accordion-list")) {
        //   $('.collapse').collapse('hide');
      }
    });

    $("#featureMore").click(function() {
      $("#featurelist li:hidden")
        .slice(0, 5)
        .slideDown();
          $("#featureMore").css({"display":"none"});
    });
  },
  head() {
    return {
      title: "Property Management Software for Commercial Real Estates | Facilio",
      meta: [
        {
          hid: "description",
          name: "description",
          content: "Enhance the tenant experience in your properties, reduce operational costs, and become more sustainable with portfolio wide data centralization and analytics."
        },
        {
          hid: "fb-share-title",
          property: "og:title",
          content: "Property Management Software for Commercial Real Estates | Facilio"
        },
        {
          hid: "fb-share-description",
          property: "og:description",
          content: "Enhance the tenant experience in your properties, reduce operational costs, and become more sustainable with portfolio wide data centralization and analytics."
        },
        {
          hid: "fb-share-image",
          property: "og:image",
          content:
            "https://facilio.com/images/og-images/commercial-portfolios.png"
        },
        {
          hid: "fb-share-url",
          property: "og:url",
          content: "https://facilio.com/industry/commercial-portfolios"
        },
        {
          hid: "twitter-meta",
          name: "twitter:card",
          content: "summary_large_image"
        },
        {
          hid: "twitter-title",
          name: "twitter:title",
          content: "Property Management Software for Commercial Real Estates | Facilio"
        },
        {
          hid: "twitter-description",
          name: "twitter:description",
          content: "Enhance the tenant experience in your properties, reduce operational costs, and become more sustainable with portfolio wide data centralization and analytics."
        },
        {
          hid: "twitter-image",
          name: "twitter:image",
          content: "https://facilio.com/images/og-images/commercial-portfolios.png"
        },
        {
          hid: "twitter-url",
          name: "twitter:url",
          content: "https://facilio.com/industry/commercial-portfolios"
        }
      ],
      link: [
        {
          rel: "canonical",
          href: "https://facilio.com/industry/commercial-portfolios"
        }
      ],
      script: [
        { src: "../../js/page.js" },
        { src: "../../js/waypoints.min.js" },
        { src: "../../js/includes.js" }
      ]
    };
  }
};
</script>

<style>
#featurelist li:nth-child(n + 6) {
  display: none;
}
.book-list li {
  padding-bottom: 7px !important;
}
</style>
